### ISSUE TITLE
Tags insert extra ',' character

### ISSUE THREAD

**Issue by kobaz** [pwman3/pwman3#65]
If i insert a password entry with tags:
foo bar,bar

It inserts a ',' in the first tag, which is supposed to be 'foo bar'

And then tags winds up being saved as:
foo,bar,bar

Instead of:
foo bar,bar

**Comment by oz123** [comment]
This is because the tags insert mechanism understands tags as separated by `" "` (an empty space).
I never thought somebody will use a two words tag.

Here is a suggestion for a fix:

instead of this https://github.com/pwman3/pwman3/blob/develop/pwman/ui/baseui.py#L217

One should use:
```
>>> tag_separator=" "
>>> re.split(r'(?<!\\)%s' % tag_separator, 'foo\ bar bla')
['foo\\ bar', 'bla']
```

You can submit a patch for that too if you want. I'll probably need some time for that, because I am quite buried with other projects now.
